spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/restructuring_dev
    username: restructuring
    password: restructuring
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none          # Flyway styrer schema i dev (riktig!)
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  sql:
    init:
      mode: always
      data-locations: classpath:data-test.sql
      # schema.sql må IKKE kjøres her, Flyway gjør jobben

  flyway:
    enabled: true
    locations: classpath:migration

jwt:
  secret: MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=
